Improvement:
anttiviljami/human-filetypes pull request #4
Opened 2023-09-18 23:15 UTC by keremnalbant

* Add uppercase support for fromExtension
* Add regarding tests

2023-09-18 23:20 UTC, keremnalbant commented
https://answers.microsoft.com/en-us/windows/forum/all/file-extensions-capitalized/c31e48ef-ab94-40ed-b55f-0ebe744e2f4d

On some Windows machines, file extensions are auto-capitalized. I thought it would be great to handle this on our end

2023-09-19 07:54 UTC, anttiviljami requested changes

2023-09-19 07:54 UTC, anttiviljami commented on src/ext.test.ts
>      });
Not a fan of this change. This makes tests harder to read and understand.

2023-09-19 07:55 UTC, anttiviljami commented
I don't like the change to make tests more clever.

Otherwise looks ok to me.

2023-09-19 07:57 UTC, anttiviljami commented on src/ext.test.ts
> +      testCases.push([ext?.toUpperCase(), type]);
Please don't hide this here. There should be an explicit test to describe the behaviour that uppercase extensions are supported.

2023-09-19 17:07 UTC, merged